import type { CSSProperties } from 'react'

export const trimStyles: Record<string, CSSProperties> = {
  container: {
    borderBottom: '1px solid var(--border3)',
  },
  body: {
    padding: '0 12px 12px',
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  tabs: {
    display: 'flex',
    gap: 4,
    borderBottom: '1px solid var(--border2)',
    paddingBottom: 6,
  },
  tabBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--text-dim)',
    fontSize: 12,
    padding: '4px 10px',
    cursor: 'pointer',
    borderRadius: '3px 3px 0 0',
  },
  tabBtnActive: {
    color: 'var(--interactive)',
    background: 'var(--border2)',
  },
  tabContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  fieldLabel: {
    fontSize: 11,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  modeToggle: {
    display: 'flex',
    gap: 4,
  },
  modeBtn: {
    background: 'transparent',
    border: '1px solid var(--border3)',
    borderRadius: 4,
    color: 'var(--text-dim)',
    fontSize: 12,
    padding: '4px 12px',
    cursor: 'pointer',
  },
  modeBtnActive: {
    background: '#2a3a4a',
    border: '1px solid var(--interactive)',
    color: 'var(--interactive)',
  },
  chipRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
  },
  chip: {
    background: 'transparent',
    border: '1px solid var(--border3)',
    borderRadius: 12,
    fontSize: 11,
    fontWeight: 600,
    padding: '3px 10px',
    cursor: 'pointer',
    transition: 'all 0.1s',
  },
  matchPreview: {
    background: 'var(--panel2)',
    border: '1px solid var(--border2)',
    borderRadius: 4,
    padding: '8px 10px',
    fontSize: 12,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  matchRanges: {
    fontSize: 11,
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    wordBreak: 'break-all',
  },
  refreshBtn: {
    background: 'transparent',
    border: '1px solid var(--border3)',
    borderRadius: 3,
    color: 'var(--text-muted)',
    fontSize: 10,
    padding: '2px 6px',
    cursor: 'pointer',
  },
  textInput: {
    background: 'var(--border2)',
    border: '1px solid var(--border3)',
    borderRadius: 4,
    color: 'var(--text)',
    padding: '6px 8px',
    fontSize: 12,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  actionBtn: {
    background: 'var(--interactive)',
    border: 'none',
    borderRadius: 4,
    color: '#fff',
    padding: '7px 14px',
    fontSize: 12,
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  statusBox: {
    background: 'var(--panel2)',
    border: '1px solid var(--border3)',
    borderRadius: 4,
    padding: '8px 10px',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    fontSize: 12,
  },
  resultPath: {
    fontSize: 11,
    color: 'var(--text-muted)',
    wordBreak: 'break-all',
  },
  errorText: {
    fontSize: 12,
    color: 'var(--c-red)',
  },
  spinner: {
    display: 'inline-block',
    animation: 'spin 1s linear infinite',
    fontSize: 14,
  },
  empty: {
    color: 'var(--text-dim)',
    fontSize: 12,
    padding: '6px 0',
  },
  pickerBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    background: 'var(--panel2)',
    border: '1px solid var(--border2)',
    borderRadius: 4,
    padding: 8,
  },
  pickerBreadcrumb: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 2,
    fontSize: 11,
    color: 'var(--text-muted)',
    fontFamily: 'var(--font-mono)',
    padding: '2px 4px',
  },
  pickerPathRoot: {
    color: 'var(--text-dim)',
  },
  pickerPathSeg: {
    color: 'var(--text)',
    display: 'inline-flex',
    alignItems: 'center',
  },
  pickerPathSep: {
    color: 'var(--text-dim)',
    margin: '0 2px',
  },
  pickerList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    maxHeight: 200,
    overflowY: 'auto',
    border: '1px solid var(--border3)',
    borderRadius: 3,
    padding: 4,
    background: 'var(--panel)',
  },
  pickerEntry: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: 'transparent',
    border: 'none',
    color: 'var(--text)',
    textAlign: 'left',
    fontSize: 12,
    padding: '4px 8px',
    borderRadius: 3,
    cursor: 'pointer',
  },
  pickerEntrySelected: {
    background: 'var(--interactive-dim)',
    color: 'var(--interactive)',
    border: '1px solid var(--interactive)',
  },
  pickerIcon: {
    color: 'var(--text-dim)',
    fontSize: 11,
    width: 12,
    display: 'inline-block',
  },
  pickerHint: {
    color: 'var(--text-dim)',
    fontSize: 11,
    padding: '4px 8px',
  },
  pickerCreateRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  pickerCreateActions: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
  },
  pickerCreateToggleBtn: {
    background: 'transparent',
    border: '1px dashed var(--border3)',
    borderRadius: 4,
    color: 'var(--text)',
    fontSize: 12,
    padding: '6px 10px',
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  pickerCreateConfirmBtn: {
    background: 'var(--interactive)',
    border: 'none',
    borderRadius: 4,
    color: '#fff',
    fontSize: 12,
    padding: '6px 10px',
    cursor: 'pointer',
  },
  pickerCreateHint: {
    color: 'var(--text-muted)',
    fontSize: 11,
    fontFamily: 'var(--font-mono)',
    wordBreak: 'break-all',
  },
  pickerNewLabel: {
    fontSize: 10,
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  targetSummaryBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    background: 'var(--panel2)',
    border: '1px solid var(--border2)',
    borderRadius: 4,
    padding: '8px 10px',
  },
  targetSummaryHead: {
    fontSize: 11,
    fontWeight: 700,
    color: 'var(--text)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  targetSummaryPath: {
    color: 'var(--text)',
    fontFamily: 'var(--font-mono)',
    fontSize: 11,
    wordBreak: 'break-all',
  },
  targetSummaryCaption: {
    color: 'var(--text-muted)',
    fontSize: 11,
  },
  targetSummaryMetrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(90px, 1fr))',
    gap: 6,
  },
  targetMetric: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
    padding: '6px 8px',
    background: 'var(--panel)',
    border: '1px solid var(--border3)',
    borderRadius: 4,
  },
  targetMetricLabel: {
    color: 'var(--text-muted)',
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  targetMetricValue: {
    color: 'var(--text)',
    fontSize: 12,
    fontWeight: 600,
  },
  emptyState: {
    fontSize: 13,
    color: 'var(--color-text-dim)',
    padding: '24px',
    textAlign: 'center',
  },
}
